### ISSUE TITLE
Parsing issue when using directives

### ISSUE THREAD

**Issue by P-H-F** [biesbjerg/ng2-translate-extract#12]
When I try to extract translations which are within an element which uses a directive, the translation keys are not parsed properly.

## Sample with directive
`<button [style.background]="'lime'">{{'SomeKey_NotWorking' | translate}}</button>`

results in

`"lime'\">{{'SomeKey_NotWorking": ""`

## Sample without directive

`<button>{{'SomeKey_Working' | translate}}</button>`

results in

`"SomeKey_Working": ""`

## Version:
ng2-translate-extract: 0.4.0

Let me know when you need additional information.
Philipp

**Comment by biesbjerg** [comment]
Thanks.

A PR fixing the regexp in PipeParser is welcome!

**Comment by biesbjerg** [comment]
I'm not sure how to support both: 

`<button [attr]="'Hello World' | translate"></button>` 
... and ...
`<button [style.background]="'lime'">{{ 'Hello World' | translate }}</button>` 

... at the same time. Any ideas?

This is the current regexp: https://github.com/biesbjerg/ng2-translate-extract/blob/master/src/parsers/pipe.parser.ts#L18

**Comment by P-H-F** [comment]
I cannot make a PR right now, unfortunately.

But this works for the test cases I copied from your pipe-test.
I added `>` to the 'except-group'.

https://regex101.com/r/wLb8us/2

**Comment by biesbjerg** [comment]
Thanks!

Fixed in https://github.com/biesbjerg/ng2-translate-extract/commit/fcd37fd00025365134709f6834ece62754c14764

**Comment by Woutwo** [comment]
This issue is still existing with services.

    trans.get("You are expected at {{time}}", {time: moment.format('H:mm')}).subscribe(text => {

returns in:

    "You are expected at {{time}}', {time: resDate.format('H:mm": "",

**Comment by biesbjerg** [comment]
I can't reproduce. I added a test that is passing for me:

```
	it('should extract strings with params', () => {
		const contents = `
			@Component({ })
			export class AppComponent {
				public constructor(protected trans: TranslateService) { }
				public test() {
					trans.get("You are expected at {{time}}", {time: moment.format('H:mm')}).subscribe();
				}
			}
		`;
		const keys = parser.extract(contents, componentFilename).keys();
		expect(keys).to.deep.equal(['You are expected at {{time}}']);
	});
```
